[project]
name = "autobridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "strands-agents[ollama,openai]>=1.53.0",
    "strands-agents-tools>=0.8.6",
    "uvicorn>=0.52.1",
    "google-api-python-client>=2.199.0",
    "google-auth-httplib2>=0.4.1",
    "google-auth-oauthlib>=1.4.0",
]
